Converting numerical data to categorical data

In [147]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

In [148]:
data = pd.read_csv("titanic_dataset.csv")
data.sample(4)
x = data[['Age','Fare']]

In [115]:
x.isnull().sum()

Age     177
Fare      0
dtype: int64

In [122]:
from sklearn.model_selection import train_test_split
xtrain,xtest = train_test_split(x,test_size=0.2)
print(xtrain.shape)
print(xtest.shape)

(712, 2)
(179, 2)


In [123]:
from sklearn.impute import SimpleImputer
smp = SimpleImputer()

xtrain_trans = smp.fit_transform(xtrain)
xtest_trans = smp.transform(xtest)

In [124]:
print(xtrain_trans)
print("\n\n")
print(xtest_trans)

[[ 21.       8.4333]
 [ 22.      49.5   ]
 [ 58.     146.5208]
 ...
 [ 22.       7.775 ]
 [ 40.5      7.75  ]
 [ 32.5     13.    ]]



[[ 27.          12.475     ]
 [ 36.          13.        ]
 [ 40.         153.4625    ]
 [ 26.          16.1       ]
 [ 29.51094571   7.7333    ]
 [ 28.           7.8958    ]
 [ 29.51094571   0.        ]
 [ 29.           7.0458    ]
 [ 36.          24.15      ]
 [ 42.          27.        ]
 [ 50.           8.05      ]
 [ 29.51094571   7.05      ]
 [ 33.          90.        ]
 [ 29.          10.5       ]
 [ 29.51094571   7.8958    ]
 [ 29.51094571  16.1       ]
 [ 22.           7.125     ]
 [  0.75        19.2583    ]
 [ 29.51094571  56.4958    ]
 [ 29.51094571  25.925     ]
 [  1.          46.9       ]
 [ 35.          52.        ]
 [ 29.51094571   7.75      ]
 [ 51.          61.3792    ]
 [ 16.           8.05      ]
 [  1.          39.        ]
 [ 51.          12.525     ]
 [ 47.          25.5875    ]
 [ 29.51094571   7.8792    ]
 [ 33.          20.525  

# Binning

we use sklearn's KBinsDiscretizer and try different strategy 

In [125]:
from sklearn.preprocessing import KBinsDiscretizer

In [126]:
K_bin = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')

In [127]:
xtrain_trs = K_bin.fit_transform(xtrain_trans)
xtest_trs = K_bin.transform(xtest_trans)

In [132]:
print(xtrain_trs[0:5],"\n\n",xtrain_trans[0:5])

[[2. 3.]
 [2. 8.]
 [8. 9.]
 [1. 3.]
 [5. 1.]] 

 [[ 21.           8.4333    ]
 [ 22.          49.5       ]
 [ 58.         146.5208    ]
 [ 20.           8.05      ]
 [ 29.51094571   7.75      ]]


# Binarization

Converting Continous value to discrete values

In [134]:
from sklearn.preprocessing import Binarizer

In [141]:
data2 = pd.read_csv("C:\\Users\\Geetanshu Dev\\Documents\\csv for Ml\\titanic_dataset.csv")
data2.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [143]:

x = data2['Age']
xtrains,xtests = train_test_split(x,test_size=0.2)
print(xtrains,xtests)
print("\n\n")
print(xtrains.shape)
print(xtests.shape)

115    21.0
538     NaN
673    31.0
324     NaN
20     35.0
       ... 
36      NaN
840    20.0
668    43.0
356    22.0
482    50.0
Name: Age, Length: 712, dtype: float64 649    23.0
245    44.0
248    37.0
369    24.0
651    18.0
       ... 
1      38.0
648     NaN
855    18.0
339    45.0
409     NaN
Name: Age, Length: 179, dtype: float64



(712,)
(179,)


In [146]:
bin = Binarizer(copy=False)
xtrain_btrs = bin.fit_transform(xtrain_trans)
xtest_btrs = bin.transform(xtest_trans)

print(xtrain_btrs)
print("\n\n")
print(xtest_btrs)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]



[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 