In [126]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

In [127]:
data = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Credit%20Default.csv")
data.sample(6)

Income        Age         Loan  Loan to Income  Default
174   39772.11873  43.725448  5492.893689        0.138109        0
574   58147.79986  34.058645  3951.189747        0.067951        0
870   29761.04601  21.854291  3748.258124        0.125945        1
1935  33707.80104  59.917644   321.578931        0.009540        0
1447  20126.41377  36.460944  1432.355862        0.071168        0
539   62908.35748  51.146827  3213.898146        0.051089        0

# Method1



In [128]:
x = data.iloc[:,0:4]
y = data.iloc[:,4:5]
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(1600, 4)
(400, 4)
(1600, 1)
(400, 1)


In [129]:
knn = KNeighborsClassifier()
knn.fit(xtrain,ytrain)
ypred = knn.predict(xtest)
acc = accuracy_score(ypred,ytest)
print(acc*100)

82.5


# Method 2

In [130]:
pca = PCA(n_components=2)
xtrain_pc = pca.fit_transform(xtrain)
xtest_pc = pca.transform(xtest)

In [131]:
knn.fit(xtrain_pc,ytrain)
ypred1 = knn.predict(xtest_pc)
acc1 = accuracy_score(ypred1,ytest)
print(acc1*100)

82.5


In [132]:
xtrain_pc

array([[ -9000.82568353,    890.87853367],
       [-23383.67770164,  -5195.58157536],
       [ 18926.44170487,   1582.47641339],
       ...,
       [-11726.36269017,  -3920.92015551],
       [  4519.94914075,   2475.85558035],
       [-23718.42029871,   -525.7816098 ]])

In [133]:
xtest_pc

array([[-2.37378158e+04, -5.13350579e+02],
       [ 3.51096144e+03, -1.71646346e+03],
       [ 1.74408846e+03, -1.47604107e+03],
       [ 1.07327374e+04, -6.03194509e+02],
       [ 2.58484858e+03,  1.91207797e+03],
       [-2.25871772e+04, -2.57196277e+03],
       [ 5.91991903e+03, -3.57926079e+03],
       [ 1.92298339e+04,  7.10835253e+02],
       [-1.34140114e+04, -1.07132736e+03],
       [-7.80495061e+03,  4.52493174e+03],
       [ 2.13640020e+04, -1.60540676e+03],
       [-1.68280090e+04,  1.91815584e+03],
       [ 6.77612936e+03, -3.45138382e+03],
       [ 1.08740959e+04, -3.31871998e+03],
       [ 7.23180797e+03,  1.84445973e+03],
       [-1.74709455e+04,  3.38762755e+02],
       [-1.69241818e+04, -5.95548987e+03],
       [ 1.38589886e+04, -8.63168655e+02],
       [-6.75828710e+03,  3.67615692e+03],
       [-1.85022280e+04, -4.63494489e+03],
       [-8.11852206e+03, -1.59151477e+03],
       [ 1.32455892e+04,  2.09050530e+01],
       [-2.19881054e+03,  1.94006177e+03],
       [-1.

# Method 3

In [134]:
data = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Credit%20Default.csv")
data.sample(6)

Income        Age         Loan  Loan to Income  Default
1854  54957.44967  59.506367  6976.463275        0.126943        0
1595  39395.83041  36.370471  7557.873338        0.191844        0
574   58147.79986  34.058645  3951.189747        0.067951        0
969   23066.96468  33.091353  1933.353568        0.083815        0
1723  26615.52430  53.350322  3458.193614        0.129931        0
1919  26095.02691  58.102091  5143.490416        0.197106        0

In [135]:
scale = StandardScaler()
xtr = scale.fit_transform(x)

In [136]:
xscale = np.array(xtr)

In [137]:
xscale

array([[ 1.45393393,  1.36433286,  1.20281942,  0.41894954],
       [-0.76217555,  0.54226845,  0.69642695,  1.60311545],
       [ 0.83682073,  1.67287749,  1.17471147,  0.72105536],
       ...,
       [-0.07122592, -0.97366665,  0.35420081,  0.45538524],
       [-0.11000289,  1.73802098, -0.92675625, -1.06442672],
       [ 1.682986  ,  1.1483008 ,  0.96381038,  0.1365212 ]])

In [138]:
xscaleT = xscale.T
xscaleT

array([[ 1.45393393, -0.76217555,  0.83682073, ..., -0.07122592,
        -0.11000289,  1.682986  ],
       [ 1.36433286,  0.54226845,  1.67287749, ..., -0.97366665,
         1.73802098,  1.1483008 ],
       [ 1.20281942,  0.69642695,  1.17471147, ...,  0.35420081,
        -0.92675625,  0.96381038],
       [ 0.41894954,  1.60311545,  0.72105536, ...,  0.45538524,
        -1.06442672,  0.1365212 ]])

In [139]:
cov_mat = np.cov(xscaleT)
cov_mat

array([[ 1.00050025, -0.03500134,  0.44133717, -0.01987222],
       [-0.03500134,  1.00050025,  0.00656429,  0.02159911],
       [ 0.44133717,  0.00656429,  1.00050025,  0.84791923],
       [-0.01987222,  0.02159911,  0.84791923,  1.00050025]])

In [140]:
eig_vals,eig_vec = np.linalg.eig(cov_mat)
print("Eigen Values = \n",eig_vals)
print("\n")
print("Eigen Vector = \n",eig_vec)

Eigen Values = 
 [1.94841957 0.03635153 1.05035687 0.96687303]


Eigen Vector = 
 [[ 0.31712772 -0.33528487 -0.68801719 -0.56004144]
 [ 0.00753178 -0.00294102  0.63421493 -0.77311451]
 [ 0.71004212  0.70404495 -0.01155235 -0.00523778]
 [ 0.62866006 -0.62601606  0.35251994  0.2976913 ]]


In [162]:
PC = eig_vec[0:2]
PC.T

array([[ 0.31712772,  0.00753178],
       [-0.33528487, -0.00294102],
       [-0.68801719,  0.63421493],
       [-0.56004144, -0.77311451]])

In [163]:
x

Income        Age         Loan  Loan to Income
0     66155.92510  59.017015  8106.532131        0.122537
1     34415.15397  48.117153  6564.745018        0.190752
2     57317.17006  63.108049  8020.953296        0.139940
3     42709.53420  45.751972  6103.642260        0.142911
4     66952.68885  18.584336  8770.099235        0.130990
...           ...        ...          ...             ...
1995  59221.04487  48.518179  1926.729397        0.032535
1996  69516.12757  23.162104  3503.176156        0.050394
1997  44311.44926  28.017167  5522.786693        0.124636
1998  43756.05660  63.971796  1622.722598        0.037086
1999  69436.57955  56.152617  7378.833599        0.106267

[2000 rows x 4 columns]

In [164]:
transform = np.dot(x,PC.T)

In [165]:
transform

array([[15382.58779113,  5639.28730479],
       [ 6381.10194718,  4422.37770576],
       [12637.07189812,  5518.41488426],
       ...,
       [10243.1529545 ,  3836.19912586],
       [12738.32768283,  1358.49908472],
       [16924.61284362,  5202.50019936]])

In [166]:
datas = pd.DataFrame(transform,columns=['PC1','PC2'])

In [167]:
datas['target'] = y

In [168]:
datas

PC1          PC2  target
0     15382.587791  5639.287305       0
1      6381.101947  4422.377706       0
2     12637.071898  5518.414884       0
3      9329.546228  4192.454841       0
4     15192.269815  6066.244899       1
...            ...          ...     ...
1995  17438.726093  1667.832595       0
1996  19627.451186  2745.239735       0
1997  10243.152954  3836.199126       1
1998  12738.327683  1358.499085       0
1999  16924.612844  5202.500199       0

[2000 rows x 3 columns]

In [169]:
x1 = datas.iloc[:,0:2]
y1 = datas.iloc[:,2:3]
xtrain1,xtest1,ytrain1,ytest1 = train_test_split(x1,y1,test_size=0.2,random_state=42)
print(xtrain1.shape)
print(xtest1.shape)

(1600, 2)
(400, 2)


In [170]:
knn.fit(xtrain1,ytrain1)
ypred2 = knn.predict(xtest1)
acc2 = accuracy_score(ypred2,ytest1)
print(acc2*100)

82.25


In [171]:
xcty = {
    'Method':['Simple One','PCA method','Calculated PCA'],
    'Accuracy':[acc,acc1,acc2]
}

datatr = pd.DataFrame(xcty)
datatr

Method  Accuracy
0      Simple One    0.8250
1      PCA method    0.8250
2  Calculated PCA    0.8225